---
version: "3"
services:
  strapi:
    container_name: strapi
    image: strapi:test
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: strapiDB
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: poeiwjrb34598b3p45b093h98p455g3nn2
      JWT_SECRET: 98ih34nv38947hb93n23np9g8h02b
      ADMIN_JWT_SECRET: 0982y49p8ghi35onhg5034h29hb2349b48h3b553
      APP_KEYS: 9238h4v9o345nb3409b-023jbv3o9b0[345b
      API_TOKEN_SALT: 982352hljg92w8gjsdhg9823gy942gb
      NODE_ENV: production
    volumes:
      - ./strapi:/srv/app
    ports:
      - "1337:1337"
    networks:
      - strapi
    depends_on:
      - strapiDB

  strapiDB:
    container_name: strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: poeiwjrb34598b3p45b093h98p455g3nn2
      POSTGRES_DB: strapi
    volumes:
      - strapi-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder
    ports:
      - "5432:5432"
    networks:
      - strapi
  client:
    container_name: client
    image: client:test
    restart: unless-stopped
    environment:
      REACT_APP_API_HOST: http://194.87.234.51:1337
    ports:
      - "3000:3000"
    networks:
      - strapi
    depends_on:
      - strapi
volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
